# Generated by Django 6.0.6 on 2026-08-24 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tv', 'TV'), ('pizarra', 'Pizarra'), ('proyector', 'Proyector'), ('wifi', 'Wifi'), ('aire_acondicionado', 'Aire acondicionado'), ('cafetera', 'Cafetera')], max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
