# Generated by Django 6.0.6 on 2026-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
